module.exports = {
  "DEV_API": process.env.DEV_API,
  "SESSION_SECRET": process.env.SESSION_SECRET,
  "CLOUDINARY_API_KEY": process.env.CLOUDINARY_API_KEY,
  "CLOUDINARY_API_SECRET": process.env.CLOUDINARY_API_SECRET,
  "CLOUDINARY_ENV": process.env.CLOUDINARY_ENV,
  "CLOUDINARY_UPLOAD_PRESET": process.env.CLOUDINARY_UPLOAD_PRESET,
  "CLOUDINARY_UPLOAD_URL": process.env.CLOUDINARY_UPLOAD_URL,
  "CLOUDINARY_CLOUD_NAME": process.env.CLOUDINARY_CLOUD_NAME,
  "TRANSPORTER_USER": process.env.TRANSPORTER_USER,
  "TRANSPORTER_PASS": process.env.TRANSPORTER_PASS,
  "TWILIO_ACCOUNT_SID": process.env.TWILIO_ACCOUNT_SID,
  "TWILIO_API_KEY": process.env.TWILIO_API_KEY,
  "TWILIO_API_SECRET": process.env.TWILIO_API_SECRET
}