export const CHANGEINFO_REQUEST = 'CHANGEINFO_REQUEST';
export const CHANGEINFO_SUCCESS = 'CHANGEINFO_SUCCESS';
export const CHANGEINFO_FAILED = 'CHANGEINFO_FAILED';

export const SENDEMAIL_REQUEST = 'SENDEMAIL_REQUEST';
export const SENDEMAIL_SUCCESS = 'SENDEMAIL_SUCCESS';
export const SENDEMAIL_FAILED = 'SENDEMAIL_FAILED';

export const FRIENDSLIST_REQUEST = 'FRIENDSLIST_REQUEST';
export const FRIENDSLIST_SUCCESS = 'FRIENDSLIST_SUCCESS';
export const FRIENDSLIST_FAILED = 'FRIENDSLIST_FAILED';

export const SENDMESSAGE_REQUEST = 'SENDMESSAGE_REQUEST';
export const SENDMESSAGE_SUCCESS = 'SENDMESSAGE_SUCCESS';
export const SENDMESSAGE_FAILED = 'SENDMESSAGE_FAILED';

export const RECEIVEMESSAGES_REQUEST = 'RECEIVEMESSAGES_REQUEST';
export const RECEIVEMESSAGES_SUCCESS = 'RECEIVEMESSAGES_SUCCESS';
export const RECEIVEMESSAGES_FAILED = 'RECEIVEMESSAGES_FAILED';