export const CHANGEINFO_REQUEST = 'CHANGEINFO_REQUEST';
export const CHANGEINFO_SUCCESS = 'CHANGEINFO_SUCCESS';
export const CHANGEINFO_FAILED = 'CHANGEINFO_FAILED';

export const SENDEMAIL_REQUEST = 'SENDEMAIL_REQUEST';
export const SENDEMAIL_SUCCESS = 'SENDEMAIL_SUCCESS';
export const SENDEMAIL_FAILED = 'SENDEMAIL_FAILED';